# spring:
#   datasource:
#     url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
#     username: ${DB_USER}
#     password: ${DB_PASSWORD}

spring:
  datasource:
    #url: jdbc:sqlserver://localhost:1433;databaseName=db_financial_dashboard;encrypt=false;trustServerCertificate=true
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=db_financial_dashboard;encrypt=false;trustServerCertificate=true
    username: admin_financial_dashboard
    password: ApiFinancialDashboard132!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver